_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
check_point:
    value: 0
data_path:
    value: /root/autodl-tmp/shared_data/projection/raw
device:
    value: cuda
dropout:
    value: 0
early_stop:
    value: true
epochs:
    value: 600
exp_group:
    value: stage_8-16
exp_id:
    value: EXP_2024.12.1.9
exp_name:
    value: MSE
if_extraction:
    value: false
if_infer:
    value: false
if_load_weight:
    value: false
loss_method:
    value: MSE
lr:
    value: 0.0002
net:
    value: unet
norm:
    value: false
patience:
    value: 15
scheduler:
    value: true
stage:
    value: 8-16
tmax:
    value: 20
wandb:
    value: online
