_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 8
check_point:
    value: 0
if_load_weight:
    value: false
learning_rate:
    value: 0.0001
loss_method:
    value: Perceptual
model_stage:
    value: 8-16
