_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 8
check_point:
    value: 0
data_path:
    value: /home/mrb2/experiments/graduation_project/shared_data/projection/raw
device:
    value: cuda
dropout:
    value: 0
early_stop:
    value: true
epochs:
    value: 200
exp_group:
    value: arch_v2
exp_id:
    value: EXP_2024.12.1.9
exp_name:
    value: channel_config
if_extraction:
    value: false
if_infer:
    value: false
if_load_weight:
    value: false
loss_method:
    value: Combined_loss
lr:
    value: 0.0001
net:
    value: unet
norm:
    value: false
patience:
    value: 10
scheduler:
    value: true
stage:
    value: 8-16
suffix:
    value: dropout
tmax:
    value: 20
wandb:
    value: online
